//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MintDParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MintDParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IMintDParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] MintDParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] MintDParser.PrimitiveTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] MintDParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] MintDParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] MintDParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] MintDParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] MintDParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] MintDParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] MintDParser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] MintDParser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] MintDParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] MintDParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] MintDParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] MintDParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionSpecifier([NotNull] MintDParser.FunctionSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionSpecifier([NotNull] MintDParser.FunctionSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaration([NotNull] MintDParser.FunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaration([NotNull] MintDParser.FunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] MintDParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] MintDParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] MintDParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] MintDParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MintDParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MintDParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.embeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmbeddedStatement([NotNull] MintDParser.EmbeddedStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.embeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmbeddedStatement([NotNull] MintDParser.EmbeddedStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationStatement([NotNull] MintDParser.DeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationStatement([NotNull] MintDParser.DeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.nullStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullStatement([NotNull] MintDParser.NullStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.nullStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullStatement([NotNull] MintDParser.NullStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] MintDParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] MintDParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectionStatement([NotNull] MintDParser.SelectionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectionStatement([NotNull] MintDParser.SelectionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] MintDParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] MintDParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStatement([NotNull] MintDParser.ElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStatement([NotNull] MintDParser.ElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatement([NotNull] MintDParser.SwitchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatement([NotNull] MintDParser.SwitchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.switchCases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchCases([NotNull] MintDParser.SwitchCasesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.switchCases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchCases([NotNull] MintDParser.SwitchCasesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseStatement([NotNull] MintDParser.CaseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseStatement([NotNull] MintDParser.CaseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.caseLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseLabel([NotNull] MintDParser.CaseLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.caseLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseLabel([NotNull] MintDParser.CaseLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIterationStatement([NotNull] MintDParser.IterationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIterationStatement([NotNull] MintDParser.IterationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] MintDParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] MintDParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] MintDParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] MintDParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.forInitExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForInitExp([NotNull] MintDParser.ForInitExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.forInitExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForInitExp([NotNull] MintDParser.ForInitExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.forCondExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForCondExp([NotNull] MintDParser.ForCondExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.forCondExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForCondExp([NotNull] MintDParser.ForCondExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.forLoopExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoopExp([NotNull] MintDParser.ForLoopExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.forLoopExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoopExp([NotNull] MintDParser.ForLoopExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpStatement([NotNull] MintDParser.JumpStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpStatement([NotNull] MintDParser.JumpStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementList([NotNull] MintDParser.StatementListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementList([NotNull] MintDParser.StatementListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.local_variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocal_variable_declaration([NotNull] MintDParser.Local_variable_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.local_variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocal_variable_declaration([NotNull] MintDParser.Local_variable_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_declarator([NotNull] MintDParser.Variable_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_declarator([NotNull] MintDParser.Variable_declaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] MintDParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] MintDParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_operator([NotNull] MintDParser.Assignment_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_operator([NotNull] MintDParser.Assignment_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.assignmentExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExp([NotNull] MintDParser.AssignmentExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.assignmentExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExp([NotNull] MintDParser.AssignmentExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.nonAssignmentExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonAssignmentExp([NotNull] MintDParser.NonAssignmentExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.nonAssignmentExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonAssignmentExp([NotNull] MintDParser.NonAssignmentExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.conditionalOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalOrExp([NotNull] MintDParser.ConditionalOrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.conditionalOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalOrExp([NotNull] MintDParser.ConditionalOrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.conditionalAndExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalAndExp([NotNull] MintDParser.ConditionalAndExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.conditionalAndExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalAndExp([NotNull] MintDParser.ConditionalAndExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.equalityExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExp([NotNull] MintDParser.EqualityExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.equalityExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExp([NotNull] MintDParser.EqualityExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.relationalExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExp([NotNull] MintDParser.RelationalExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.relationalExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExp([NotNull] MintDParser.RelationalExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.additiveExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExp([NotNull] MintDParser.AdditiveExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.additiveExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExp([NotNull] MintDParser.AdditiveExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.multiplicativeExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExp([NotNull] MintDParser.MultiplicativeExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.multiplicativeExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExp([NotNull] MintDParser.MultiplicativeExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.unaryExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExp([NotNull] MintDParser.UnaryExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.unaryExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExp([NotNull] MintDParser.UnaryExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.typeCast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeCast([NotNull] MintDParser.TypeCastContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.typeCast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeCast([NotNull] MintDParser.TypeCastContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperator([NotNull] MintDParser.UnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperator([NotNull] MintDParser.UnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.preIncDecExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreIncDecExp([NotNull] MintDParser.PreIncDecExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.preIncDecExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreIncDecExp([NotNull] MintDParser.PreIncDecExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.postfixExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExp([NotNull] MintDParser.PostfixExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.postfixExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExp([NotNull] MintDParser.PostfixExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix([NotNull] MintDParser.PostfixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix([NotNull] MintDParser.PostfixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.methodInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodInvocation([NotNull] MintDParser.MethodInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.methodInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodInvocation([NotNull] MintDParser.MethodInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.methodExtern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodExtern([NotNull] MintDParser.MethodExternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.methodExtern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodExtern([NotNull] MintDParser.MethodExternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] MintDParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] MintDParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.memberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberAccess([NotNull] MintDParser.MemberAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.memberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberAccess([NotNull] MintDParser.MemberAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.primaryExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExp([NotNull] MintDParser.PrimaryExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.primaryExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExp([NotNull] MintDParser.PrimaryExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.parenthExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthExp([NotNull] MintDParser.ParenthExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.parenthExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthExp([NotNull] MintDParser.ParenthExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.localizeExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalizeExp([NotNull] MintDParser.LocalizeExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.localizeExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalizeExp([NotNull] MintDParser.LocalizeExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.localizeParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalizeParams([NotNull] MintDParser.LocalizeParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.localizeParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalizeParams([NotNull] MintDParser.LocalizeParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MintDParser.localizeParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalizeParam([NotNull] MintDParser.LocalizeParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MintDParser.localizeParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalizeParam([NotNull] MintDParser.LocalizeParamContext context);
}
